services:
  api_gemini_postgres:
    container_name: dev-api-gemini-postgres
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=dev-api-gemini
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
