services:
  api_gemini_postgres:
    container_name: dev-api-gemini-postgres
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=dev-api-gemini
    networks:
      - network_api_gemini_express
    volumes:
      - postgres_data:/bitnami/postgresql

  api_gemini_redis:
    container_name: dev-api-gemini-redis
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - network_api_gemini_express
    volumes:
      - redis_data:/data

networks:
  network_api_gemini_express:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
